# Site Settings
title: "Listen"
description: >
    "Blank"
baseurl: ""
url: "https://github.com/CVSSP/sisec-mus-18-pick-the-best"

github:
    username: "CVSPP"
    repository : "sisec-mus-18-pick-the-best"
    branch: "gh-pages"

# Build Setting
include: 
    - '_pages'
exclude:
  - package.json
  - node_modules
  - gulpfile.js

kramdown:
  input: GFM
